### ISSUE TITLE
Crear metodes API per poder fer les operacions basiques CRUD a totes les taules que no siguin de enums.

### ISSUE THREAD

**Issue by JaumeFP** [CIFP-Pau-Casesnoves-DAW/projecte-22-23-etv-equipo-sol#6]
- Metodes API per poder fer les operacions basiques CRUD: Entenem aixo com a tots els endpoints necesaris per poder fer un select de tota la taula, un select per id, un insert, un update i un delete per id.

**Comment by tcampaner** [comment]
Es correcta.Després parlarem d'alguns endpoints adicionals.

Sent from Yahoo Mail on Android 
 
  On dv., de gen. 6, 2023 at 5:39 p. m., ***@***.***> wrote:   

   
   - Metodes API per poder fer les operacions basiques CRUD: Entenem aixo com a tots els endpoints necesaris per poder fer un select de tota la taula, un select per id, un insert, un update i un delete per id.
